---
version: '2.4'
services:
  samba:
    hostname: medium
    image: scontx:v0
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: /srv
        target: /srv
networks:
  default:
