#!/bin/bash

BTPL=$1
shift
BLDDIR=$1
shift
CTPL=$1
shift
IMGNAME=$1
shift
IMGVERS=$1
shift
COMPOSE=$1

if [ "$1" = "" ]; then
	echo "need btpl builddir ctmpl imgname imgvers composefile"
	exit 1
fi

if [ ! -e "$CTPL" ]; then
	echo "dockerfile template does not exist"
	exit 1
fi

if [ ! -e "$CTPL" ]; then
	echo "compose template does not exist"
	exit 1
fi

if [ ! -d "$BLDDIR" ]; then
	echo "build dir does not exist"
	exit 1
fi


read -s -p "provide fameltern password: " pass1
echo ""
read -s -p "repeat  fameltern password: " pass2
echo ""

if [ "$pass1" != "$pass2" ]; then
	echo "passwords do not match"
	exit 1
fi

cp -f "$BTPL" "$BLDDIR/Dockerfile"
sed -i "s/%passwd%/$pass1/g"  "$BLDDIR/Dockerfile"
chmod go-r "$BLDDIR/Dockerfile"

cp -f "$CTPL" "$COMPOSE"
sed -i "s/%imgname%/$IMGNAME:$IMGVERS/g"  "$COMPOSE"

echo "done"
