#!/bin/bash

CTPL=$1
shift
IMGNAME=$(echo $1 | sed -e 's/\//\\\//')
shift
IMGVERS=$(echo $1 | sed -e 's/\//\\\//')
shift
COMPOSE=$(echo $1 | sed -e 's/\//\\\//')
shift
VOLSRC=$(echo $1 | sed -e 's/\//\\\//')
shift
VOLDST=$(echo $1 | sed -e 's/\//\\\//')
shift
HNAME=$1

if [ "$1" = "" ]; then
	echo "need ctmpl imgname imgvers composefile vol-src vol-dest host-name"
	exit 1
fi

if [ ! -e "$CTPL" ]; then
	echo "compose template does not exist"
	exit 1
fi

cp -f "$CTPL" "$COMPOSE"
sed -i "s/%imgname%/$IMGNAME:$IMGVERS/g"  "$COMPOSE"
sed -i "s/%volsrc%/$VOLSRC/g"  "$COMPOSE"
sed -i "s/%voldst%/$VOLDST/g"  "$COMPOSE"
sed -i "s/%hostname%/$HNAME/g" "$COMPOSE"
