#!/bin/bash

BTPL=$1
shift
BLDDIR=$1
shift
USERN=$1

if [ "$1" = "" ]; then
	echo "need btpl builddir user"
	exit 1
fi

if [ ! -e "$BTPL" ]; then
	echo "docker file template does not exist"
	exit 1
fi

if [ ! -d "$BLDDIR" ]; then
	echo "build dir does not exist"
	exit 1
fi

read -s -p "provide $USERN password: " pass1
echo ""
read -s -p "repeat  $USERN password: " pass2
echo ""

if [ "$pass1" != "$pass2" ]; then
	echo "passwords do not match"
	exit 1
fi

hash=$(echo "$pass1" | mkpasswd -m sha-512 -s | sed -e 's/\//\\\//g' -e 's/\$/\\$/g')

cp -f "$BTPL" "$BLDDIR/Dockerfile"
sed -i "s/%passwd%/$pass1/g"   "$BLDDIR/Dockerfile"
sed -i "s/%username%/$USERN/g" "$BLDDIR/Dockerfile"
sed -i "s/%passhash%/$hash/g"  "$BLDDIR/Dockerfile"
chmod go-r "$BLDDIR/Dockerfile"

