FROM debian:10-slim

ADD ./docker-entrypoint.sh /

RUN apt-get update && apt-get install -y \
  samba

RUN useradd -m -p "%passhash%" -s /bin/bash %username%

ADD smb.conf.part /tmp
RUN cat /tmp/smb.conf.part >> /etc/samba/smb.conf
RUN (echo "%passwd%"; echo "%passwd%") | smbpasswd -s -a %username%

EXPOSE 445

CMD /docker-entrypoint.sh
